### ISSUE TITLE
Package issue

### ISSUE THREAD

**Issue by danielroe** [fredjens/sanity-datatable#6]
The current version of this package on NPM has no `build/index.js` as specified in `package.json` and so cannot be imported.

**Comment by fredjens** [comment]
Hi there. This is a plugin for the Sanity CMS and is not meant to be imported, but installed using: `sanity install datatable`

**Comment by danielroe** [comment]
@fredjens I am flagging up that your `package.json` is incorrect in your distributed package as it points to a nonexistent file.

**Comment by fredjens** [comment]
The file exists after the package is built from src and distributed to NPM.

**Comment by danielroe** [comment]
It does not. That is the very issue I am reporting. :slightly_smiling_face: 

See https://unpkg.com/browse/sanity-plugin-datatable@1.1.0/build/

**Comment by fredjens** [comment]
Aha, I see! Thank you for reporting, will fix in next release. Is this causing you any problems using the plugin?

**Comment by danielroe** [comment]
No rush from my point of view. It did stop me doing something when I reported it, but I can't now recall what!
